[package]
name = "tweag-gen-k8s-nickel"
version = "0.1.0"
authors = ["agondek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapi = "0.1.5"
