name: "Build & test nickel-kubernetes"
on:
  - pull_request
  - push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check
      - run: nix build
